### ISSUE TITLE
Please make sure you have the correct access rights and the repository exists.

### ISSUE THREAD

**Issue by piotrek2555** [mas94uk/upnpTube#11]
root@raspberrypi:/# git clone git@github.com:mas94uk/upnpTube.git
Cloning into 'upnpTube'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.3' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mas94uk** [comment]
This problem is your side, I think. You need to create an ssh key and add it to Github Settings -> SSH and GPG keys.
At least the same thing happens to me if I try to clone anything from github without a properly set-up SSH key.

If you think it's a problem with my repo specifically, please let me know what you think I need to change.

**Comment by mas94uk** [comment]
No response in over two months so closing.
